### ISSUE TITLE
.ldr file import error (AttributeError: 'NoneType' object has no attribute 'Name')

### ISSUE THREAD

**Issue by Zsolt98** [jonnysp/LDR2C4D#1]
I would like to open .ldr file that converted from LDD .lxf file, and I got this error message when I open it in Cinema4D R19.

Console output:

- - - - - - - - - - - -
           _           
          [_]          
       / |   | \       
      () '---'  C      
        |  |  |        
        [=|=]          
                       
LDR2C4D - 1.0.3
- - - - - - - - - - - -
Traceback (most recent call last):
  File "'LDR2C4D.pypv'", line 956, in Command
  File "'LDR2C4D.pypv'", line 1115, in Load
AttributeError: 'NoneType' object has no attribute 'Name'

Try with other .ldr file:

Traceback (most recent call last):
  File "'LDR2C4D.pypv'", line 956, in Command
  File "'LDR2C4D.pypv'", line 1115, in Load
AttributeError: 'NoneType' object has no attribute 'Name'

**Comment by jonnysp** [comment]
can you upload the ldr file?

**Comment by Zsolt98** [comment]
Yes, there is the ldr file:
https://gist.github.com/Zsolt98/2f4769690be75242e5926b71948b968b

and there is .mpd file: https://gist.github.com/Zsolt98/45ba1c9b4fa54a5d51304336fc4c28d9
it is also don't work

**Comment by jonnysp** [comment]
Thanks. 

I have no longer R19 to test.

In my R20 it works!

![grafik](https://user-images.githubusercontent.com/1651241/174824255-94d68341-1826-4a41-ad9f-7c61613dd06d.png)

Do you have the current LDRAW library?


you can also use Blender with LDRAW Plugin, then Export as OBJ or compatible Fileformat to im port in Cinema4D

good look.

**Comment by jonnysp** [comment]
or try my https://github.com/jonnysp/LDD2C4D plugin

**Comment by Zsolt98** [comment]
Yes, I updated 2 days ago the LDRAW library.
I think in my library there are older .dat files, that occurred the error. (I will try with new dowload)

I tried your LDD plugin, but the load model button is inactive.
What file is needed to select as database?
This is the 1.0.4 version.
![image](https://user-images.githubusercontent.com/48164060/174887635-7a1c4164-00db-41f3-82cb-51ed8529823f.png)

**Comment by Zsolt98** [comment]
Somehow the LDD plugin finally worked, and also get an error 😅

Console output:

- - - - - - - - - - - -
           _           
          [_]          
       / |   | \       
      () '---'  C      
        |  |  |        
        [=|=]          
                       
LDD2C4D - 1.0.4
- - - - - - - - - - - -

           _           
          [_]          
       / |   | \       
      () '---'  C      
        |  |  |        
        [=|=]          
                       
LDR2C4D - 1.0.3
- - - - - - - - - - - -

Database Brickversion: 2670
Database OK.
Traceback (most recent call last):
  File "'LDD2C4D.pypv'", line 442, in Command
  File "'LDD2C4D.pypv'", line 538, in Load
  File "'LDD2C4D.pypv'", line 94, in __init__
  File "C:\Program Files\MAXON\Cinema 4D R19\resource\modules\python\Python.win64.framework\lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'E:\\police car 7236.lxf'

**Comment by jonnysp** [comment]
hi
i have installed R19 and tryed LDR2C4D - 1.0.3 

in my case it works

![grafik](https://user-images.githubusercontent.com/1651241/174969417-bf310f26-6c13-4c29-8a05-a4141e98f383.png)


maybe you can reinstall r19 or try on another computer

good luck
